name 'ssl-tunnel-for-redis'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures ssl-tunnel-for-redis'
long_description 'Installs/Configures ssl-tunnel-for-redis'
version '0.1.0'

depends 'redisio', '~> 2.3.0'
depends 'stunnel', '~> 2.1.0'
